### ISSUE TITLE
Unable to download SDK

### ISSUE THREAD

**Issue by viewpointsa** [9crk/libhicat#2]
Download failed, please copy sdk on EU/USA file sharing server

**Comment by 9crk** [comment]
It's hard for a Chinese uploading any big file to google drive or github... :-(

**Comment by viewpointsa** [comment]
To download we must  install baidu software to use it you must have a account, to have a account you must have Chinese phone number...
Please can you upload to https://wetransfer.com/ or http://dl.free.fr/

**Comment by 9crk** [comment]
I'm still not sure whether this illegal to post this document on the Internet.
https://drive.google.com/open?id=0B9zFmn9EJ1owaEhqdHZRTWx6TGs
