### ISSUE TITLE
files hierarchie

### ISSUE THREAD

**Issue by Pascal66** [9crk/libhicat#3]
Hello
Have you a file hierarchie for all ?
I received an hicat board with sdcard reader broken so i'm trying to use the board with nfs 
Where to put the libhicat ? 
for example rstpserver need libhisv library and not found it.
Thank you
Hope Joseph send you another board quickly...

**Comment by 9crk** [comment]
hicat.tar was put under /
the path is /hicat/
sdcard only have a few unnecessary files and to store the  recording videos.

**Comment by Pascal66** [comment]
do i need to made symbolic link of /app /lib /opt from my nfs to / in hicat board ?

**Comment by 9crk** [comment]
app lib opt  are for developing. it depends on what you want to do.
if just playing with the board, you dont need it.
if you want to developing some opencv and camera stuff,  and you know how to cross-compile the code. then you'll need this three dir.

**Comment by Pascal66** [comment]
it's for dev. so I understand that i've to symlink all on the root of the board from nfs shared
I've a problem for example, even if i link libhisiv.a to /lib, rtspserver all ready send error : 

` [venc_getFrame]-414: get venc stream time out, exit thread`

**Comment by 9crk** [comment]
seems only one condition will this occur: the camera was not well connected.

**Comment by Pascal66** [comment]
thank you for your patience.
then it seems I've another problem with this card. SD & cam not working.
