### ISSUE TITLE
Suggestion for crosscompile ubuntu/windows

### ISSUE THREAD

**Issue by Pascal66** [9crk/libhicat#5]
Hello, even if I successfully installed and compiled the app, I need a suggestion to work better.
some gui are big, other are crazy to configure  with only the armlibrary and opencv
Just searching to work and crosscompile my work easilly.

Thank you for your work.

**Comment by 9crk** [comment]
what do you mean with  gui?

**Comment by Pascal66** [comment]
Like eclipse codeblocks segger or other more easy
